class Constants:
    Get_All_Products_List_URL = 'https://automationexercise.com/api/productsList'
    POST_To_All_Products_List_URL = 'https://automationexercise.com/api/productsList'
    Get_All_Brands_List_URL = 'https://automationexercise.com/api/brandsList'
    PUT_To_All_Brands_List_URL = 'https://automationexercise.com/api/brandsList'
    POST_To_Search_Product_URL = 'https://automationexercise.com/api/searchProduct'
    POST_To_Search_Product_without_URL = 'https://automationexercise.com/api/searchProduct'
    POST_To_Verify_Login_with_valid_details_URL = 'https://automationexercise.com/api/verifyLogin'
    POST_to_verify_login_without_email_parameter ='https://automationexercise.com/api/verifyLogin'
    DELETE_to_verify_login ='https://automationexercise.com/api/verifyLogin'
    POST_to_verify_login_with_invalid_details = 'https://automationexercise.com/api/verifyLogin'
    POST_To_Create_Register_User_Account = 'https://automationexercise.com/api/createAccount'
    DELETE_METHOD_To_Delete_User_Account = 'https://automationexercise.com/api/deleteAccount'
    PUT_METHOD_To_Update_User_Account = 'https://automationexercise.com/api/updateAccount'
    GET_user_account_detail_by_email = 'https://automationexercise.com/api/getUserDetailByEmail'